### ISSUE TITLE
Release 0.2

### ISSUE THREAD

**Issue by john-sandall** [CoefficientSystems/coefficient-cookiecutter#17]
- [x] #19 
- [x] #25
- [x] #26
- [x] #27
- [x] #51
- [x] #37
- [x] #56
- [x] #108 
- [x] #87 
- [x] #55 
- [x] Improve README for new users (#96)
- [x] Add towncrier entries
- [x] Release to `main`
- [x] Tag release

**Comment by john-sandall** [comment]
Released: https://github.com/CoefficientSystems/coefficient-cookiecutter/releases/tag/0.2.0
