### ISSUE TITLE
Release 0.1

### ISSUE THREAD

**Issue by john-sandall** [CoefficientSystems/coefficient-cookiecutter#3]
# Issues
- [x] #1 
- [x] #5
- [x] tutorial1 ("Getting to know")
- [x] tutorial2 ("Create from scratch")
- [x] "Project templates made easy"
- [x] #6
- [x] #8
- [x] #10
- [x] #12
- [x] Add ccds inspired data directory layout
- [x] #14
